kind: Pod
metadata:
  name: app
  labels:
    app: web
spec:
  containers:
    - name: php
      image: php-app-with-ssh
      imagePullPolicy: Never
      ports:
        - containerPort: 80
        - containerPort: 22