---
- name: Configure PHP App via Ansible
  hosts: all
  become: false
  tasks:

    - name: Ping the PHP pod
      ping:

    - name: Copy profile.php to Apache root
      copy:
        src: files/mypage.php
        dest: /var/www/html/mypage.php
        mode: '0644'